spring.application.name=gateway-service

server.port=8080


# USER SERVICE - AUTH
spring.cloud.gateway.server.webflux.routes[0].id=user-auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://user-service:8082
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**


# USER SERVICE - USERS
spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://user-service:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/users/**


# MOVIE SERVICE
spring.cloud.gateway.server.webflux.routes[2].id=movie-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://movie-service:8081
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/movies/**

# SAVED MOVIES SERVICE
spring.cloud.gateway.server.webflux.routes[5].id=saved-movies-service
spring.cloud.gateway.server.webflux.routes[5].uri=http://movie-service:8081
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/saved-movies/**


# RATING SERVICE
spring.cloud.gateway.server.webflux.routes[3].id=rating-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://rating-service:8083
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/ratings/**


# RECOMMENDATION SERVICE
spring.cloud.gateway.server.webflux.routes[4].id=recommendation-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://recommendation-service:8084
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/recommendations/**


# ACTUATOR
management.endpoints.web.exposure.include=gateway,health,info
management.endpoint.gateway.access=read_only


# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}


# DISCOVERY
spring.cloud.gateway.server.webflux.discovery.locator.enabled=false




# spring.application.name=gateway-service

# server.port=8080

# # USER SERVICE
# spring.cloud.gateway.server.webflux.routes[0].id=user-service
# spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8082
# spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**


# # MOVIE SERVICE
# spring.cloud.gateway.server.webflux.routes[1].id=movie-service
# spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8081
# spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/movies/**


# # RATING SERVICE
# spring.cloud.gateway.server.webflux.routes[2].id=rating-service
# spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
# spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/ratings/**


# # RECOMMENDATION SERVICE
# spring.cloud.gateway.server.webflux.routes[3].id=recommendation-service
# spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8084
# spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/recommendations/**


# # ACTUATOR
# management.endpoints.web.exposure.include=gateway,health,info
# management.endpoint.gateway.access=read_only


# jwt.secret=${JWT_SECRET}
# jwt.expiration=${JWT_EXPIRATION}


# # DISCOVERY
# spring.cloud.gateway.server.webflux.discovery.locator.enabled=false
