spring.application.name=rating-service

server.port=8083

spring.neo4j.uri=${SPRING_NEO4J_URI}
spring.neo4j.authentication.username=${SPRING_NEO4J_USERNAME}
spring.neo4j.authentication.password=${SPRING_NEO4J_PASSWORD}

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}


jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}