spring.application.name=user-service
server.port=8082

spring.neo4j.uri=${SPRING_NEO4J_URI}
spring.neo4j.authentication.username=${SPRING_NEO4J_USERNAME}
spring.neo4j.authentication.password=${SPRING_NEO4J_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}